"""initial clean

Revision ID: 18e1ccd022aa
Revises: 
Create Date: 2025-05-14 16:29:03.375656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18e1ccd022aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_members', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'channel_members', 'users', ['user_id'], ['id'])
    op.alter_column('channels', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'channels', 'users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'channels', 'events', ['event_id'], ['id'])
    op.add_column('messages', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('messages', 'channel_id')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.alter_column('channels', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'channel_members', type_='foreignkey')
    op.drop_column('channel_members', 'id')
    # ### end Alembic commands ###
