"""add_notifications_table

Revision ID: 38796dba3459
Revises: 7be656f94d91
Create Date: 2025-05-18 14:07:03.517305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38796dba3459'
down_revision: Union[str, None] = '7be656f94d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('date_limite_inscription', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('event_commande_participation', sa.String(), nullable=True))
    op.add_column('events', sa.Column('commodites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'address')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'commodites')
    op.drop_column('events', 'event_commande_participation')
    op.drop_column('events', 'price')
    op.drop_column('events', 'is_paid')
    op.drop_column('events', 'date_limite_inscription')
    op.drop_table('notifications')
    # ### end Alembic commands ###
