"""not nullable changements

Revision ID: 3d0929434828
Revises: b19040fd3b07
Create Date: 2025-04-26 20:20:08.722821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0929434828'
down_revision: Union[str, None] = 'b19040fd3b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_age_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'event_age_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'nombre_utilisateur_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'nombre_utilisateur_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'event_age_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'event_age_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
