"""add interests  and bibliograogy fields 

Revision ID: 75280b147072
Revises: 3d0929434828
Create Date: 2025-05-03 23:22:27.623620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75280b147072'
down_revision: Union[str, None] = '3d0929434828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'id_gestionnaire',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('bibliography', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_column('users', 'bibliography')
    op.alter_column('events', 'id_gestionnaire',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
