"""sync users table with model

Revision ID: 842dc94e27de
Revises: 7be656f94d91
Create Date: 2025-05-10 22:01:07.949006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '842dc94e27de'
down_revision: Union[str, None] = '7be656f94d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('event_image', sa.String(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.alter_column('events', 'id_gestionnaire',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'event_ville',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('events', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('events', 'event_age_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'event_age_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'nombre_utilisateur_min',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bibliography', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'familyname',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.execute("UPDATE users SET date_of_birth = '1970-01-01' WHERE date_of_birth IS NULL")
    op.alter_column('users', 'date_of_birth', existing_type=sa.DATE(), nullable=False)
    op.drop_column('users', 'age')
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('users', 'familyname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'interests')
    op.drop_column('users', 'bibliography')
    op.drop_column('users', 'profile_image')
    op.alter_column('events', 'nombre_utilisateur_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'event_age_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'event_age_min',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'event_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'event_ville',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('events', 'id_gestionnaire',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'event_image')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
